### ISSUE TITLE
NoSuchMethodError setNormalizeUri on upgrade to 2.1.0

### ISSUE THREAD

**Issue by svpace** [GoogleContainerTools/jib#2321]
**Environment**:

- *Jib version:* 2.1.0
- *Build tool:* Maven 3.6
- *OS:*  Linux

**Description of the issue**:
Build fails with "NoSuchMethodError" on "org.apache.http.client.config.RequestConfig$Builder.setNormalizeUri" when upgrading from 1.6.1 to 2.1.0. The problem seems to have been introduced on 1.8.0.

**Expected behavior**:
Build normally

**Steps to reproduce**:

Upgrade from 1.6.1 to 2.1.0

**Additional Information**:
This seems related to #2183 except that it is on Maven.

All plugins versions are already in the parent pom

**Comment by loosebazooka** [comment]
That's weird, I guess you could try putting the jib plugin first in the pom.xml? I can't remember off the top of my head how to look at the plugin classpath, so I'll look around. Historically we have seen this in gradle, so I'm not quite sure how to analyze it yet.

One option is to maybe try to force the dependency version directly on the plugin?

```xml
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>${jib-maven-plugin.version}</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.10</version>
    </dependency>
  </dependencies>
  ...
</plugin>
```

**Comment by loosebazooka** [comment]
Actually, no I think I'm wrong, maven appears to have some sort of isolation between plugin classloaders (https://maven.apache.org/guides/mini/guide-maven-classloading.html). This also suggests that the conflict is coming from maven core libraries? Weird?

Can you provide us with a sample application that fails? Also what version of java and maven are you using?

**Comment by gpreston-apex** [comment]
I'm seeing the same issue.  Adding an explicit dependency on httpclient 4.5.10 doesn't help.

**Comment by loosebazooka** [comment]
would be helpful to us if someone could include a sample project that generates this error.

**Comment by svpace** [comment]
Trimming down my pom.xml to build a minimal example revealed that the conflict was with version 1.7 of google-storage-wagon extension. Updating the extension to 2.3 solved the issue.

As explained in the link provided by @loosebazooka, it seems that extensions use the core classloader instead of isolated plugin classloader.

Thank you everyone for the help.

**Comment by chanseokoh** [comment]
Ah, that makes sense. [Maven Wagon](http://maven.apache.org/wagon/) is a transport abstraction that is used in Maven's artifact and repository handling code, so I can imagine it becomes part of the core Maven builds.
